/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.sangraj.lra.UI.Admin;

import com.sangraj.lra.UI.Admin.USDE.SearchUI;
import com.sangraj.lra.UI.Admin.USDE.UsersUI;
import com.sangraj.lra.UI.LoginUI;

/**
 *
 * @author Song Grudge Ranjit
 */
public class AdministratorUI extends javax.swing.JFrame {

    /**
     * Creates new form AdminsUI
     */
    public AdministratorUI() {
        setTitle("ADMINISTRATOR");
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        btnLogout = new javax.swing.JButton();
        btnSearch = new javax.swing.JButton();
        btnUser = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setLayout(null);

        btnLogout.setText("LOGOUT");
        btnLogout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                logOutClick(evt);
            }
        });
        jPanel1.add(btnLogout);
        btnLogout.setBounds(620, 690, 270, 120);

        btnSearch.setText("SEARCH");
        btnSearch.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                searchButtonClick(evt);
            }
        });
        jPanel1.add(btnSearch);
        btnSearch.setBounds(620, 550, 270, 120);

        btnUser.setText("USERS");
        btnUser.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                usersClick(evt);
            }
        });
        jPanel1.add(btnUser);
        btnUser.setBounds(620, 410, 270, 120);

        jLabel1.setIcon(new javax.swing.ImageIcon("C:\\Users\\Song Grudge Ranjit\\Documents\\NetBeansProjects\\ScrapperTool\\src\\com\\sangraj\\scrap\\resources\\Admin.jpg")); // NOI18N
        jPanel1.add(jLabel1);
        jLabel1.setBounds(0, -40, 990, 870);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 990, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 829, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void usersClick(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_usersClick
        UsersUI ui=new UsersUI();
        ui.setVisible(true);
        setVisible(false);
    }//GEN-LAST:event_usersClick

    private void logOutClick(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_logOutClick
        LoginUI ui=new LoginUI();
        ui.setVisible(true);
        setVisible(false);
    }//GEN-LAST:event_logOutClick

    private void searchButtonClick(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_searchButtonClick
        SearchUI ui=new SearchUI();
        ui.setVisible(true);
        setVisible(false);
    }//GEN-LAST:event_searchButtonClick


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnLogout;
    private javax.swing.JButton btnSearch;
    private javax.swing.JButton btnUser;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
