/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.sangraj.lra.UI.Admin.USDE;


import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import javax.swing.JOptionPane;


/**
 *
 * @author Song Grudge Ranjit
 */
public class EditUI extends javax.swing.JFrame {
//private Users user;
    /**
     * Creates new form EditUI
     */

    public EditUI() {
//        this.user=user;
        initComponents();
    }
//    private void populateData(){
//        txtFirstname.setText(user.getFirstname());
//        txtMiddlename.setText(user.getMiddlename());
//        txtLastname.setText(user.getLastname());
//        txtEmail.setText(user.getEmail());
//    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        btnUpdate = new javax.swing.JButton();
        txtEmail = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        btnBack = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        txtUsername = new javax.swing.JTextField();
        txtMiddlename = new javax.swing.JTextField();
        txtLastname = new javax.swing.JTextField();
        lblid = new javax.swing.JLabel();
        txtId = new javax.swing.JTextField();
        txtFirstname = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setLayout(null);

        btnUpdate.setText("UPDATE");
        btnUpdate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                updateButtonClick(evt);
            }
        });
        jPanel1.add(btnUpdate);
        btnUpdate.setBounds(170, 240, 80, 23);
        jPanel1.add(txtEmail);
        txtEmail.setBounds(220, 160, 170, 20);

        jLabel2.setForeground(new java.awt.Color(255, 255, 0));
        jLabel2.setText("EMAIL");
        jPanel1.add(jLabel2);
        jLabel2.setBounds(110, 160, 90, 20);

        btnBack.setText("CANCEL");
        btnBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cancelButtonClick(evt);
            }
        });
        jPanel1.add(btnBack);
        btnBack.setBounds(270, 240, 80, 23);

        jLabel3.setForeground(new java.awt.Color(255, 255, 0));
        jLabel3.setText("FIRST NAME");
        jPanel1.add(jLabel3);
        jLabel3.setBounds(110, 70, 90, 20);

        jLabel4.setForeground(new java.awt.Color(255, 255, 0));
        jLabel4.setText("MIDDLE NAME");
        jPanel1.add(jLabel4);
        jLabel4.setBounds(110, 100, 90, 20);

        jLabel5.setForeground(new java.awt.Color(255, 255, 0));
        jLabel5.setText("LAST NAME");
        jPanel1.add(jLabel5);
        jLabel5.setBounds(110, 130, 90, 20);

        txtUsername.setEditable(false);
        jPanel1.add(txtUsername);
        txtUsername.setBounds(220, 40, 170, 20);
        jPanel1.add(txtMiddlename);
        txtMiddlename.setBounds(220, 100, 170, 20);
        jPanel1.add(txtLastname);
        txtLastname.setBounds(220, 130, 170, 20);

        lblid.setForeground(new java.awt.Color(255, 255, 0));
        lblid.setText("ID");
        jPanel1.add(lblid);
        lblid.setBounds(110, 20, 11, 14);

        txtId.setEditable(false);
        jPanel1.add(txtId);
        txtId.setBounds(220, 10, 60, 20);
        jPanel1.add(txtFirstname);
        txtFirstname.setBounds(220, 70, 170, 20);

        jLabel6.setForeground(new java.awt.Color(255, 255, 0));
        jLabel6.setText("USERNAME");
        jPanel1.add(jLabel6);
        jLabel6.setBounds(110, 50, 80, 14);

        jLabel1.setIcon(new javax.swing.ImageIcon("C:\\Users\\Song Grudge Ranjit\\Pictures\\honeycomb-wallpaper-1.jpg")); // NOI18N
        jPanel1.add(jLabel1);
        jLabel1.setBounds(0, 0, 540, 320);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 540, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 319, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void cancelButtonClick(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancelButtonClick
        setVisible(false);
        
    }//GEN-LAST:event_cancelButtonClick

    private void updateButtonClick(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_updateButtonClick
try{
    Class.forName("com.mysql.jdbc.Driver");
    Connection conn = DriverManager.getConnection("jdbc:mysql://localhost/registration", "root", null);
    int id=Integer.parseInt(txtId.getText());
//    String id =txtId.getText();
//    String firstName=txtFirstname.getText();
//    String middleName=txtMiddlename.getText();
//    String lastName=txtLastname.getText();
//    String email=txtEmail.getText();
String sql="UPDATE tbl_registered set username=?,firstname=?,middlename=?,lastname=?,email=?WHERE user_id="+id+"";
//   String sql="INSERT INTO tbl_registered(firstname,middlename,lastname,email)VALUES(?,?,?,?) WHERE user_id="+id+"";
  //String sql="UPDATE tbl_registered"+ "SET firstname='"+firstName+"',middlename='"+middleName+"',lastname='"+lastName+"',email='"+email+"' WHERE user_id='"+id+"'";
    PreparedStatement pst=conn.prepareStatement(sql);
   int ch = JOptionPane.showOptionDialog(null, "Do you really want to change informations of the user?", "EDIT USER", JOptionPane.YES_NO_OPTION, WIDTH, null, null, "yes");
   if(ch==0){
//    String sql="UPDATE firstname='"+firstName+"',middlename='"+middleName+"',lastname='"+lastName+"',email='"+email+"'where user_id='"+id+"' FROM tbl_registered";
    pst.setString(1, txtUsername.getText());
    pst.setString(2, txtFirstname.getText());
    pst.setString(3, txtMiddlename.getText());
    pst.setString(4, txtLastname.getText());
    pst.setString(5, txtEmail.getText());
//    pst.executeQuery();
    pst.execute(); 
   JOptionPane.showMessageDialog(null, "Information Updated");
       setVisible(false);
   }else{
       
   }
}catch(Exception e){
    JOptionPane.showMessageDialog(null, e.getMessage());
}
    }//GEN-LAST:event_updateButtonClick

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBack;
    private javax.swing.JButton btnUpdate;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel lblid;
    public javax.swing.JTextField txtEmail;
    public javax.swing.JTextField txtFirstname;
    public javax.swing.JTextField txtId;
    public javax.swing.JTextField txtLastname;
    public javax.swing.JTextField txtMiddlename;
    public javax.swing.JTextField txtUsername;
    // End of variables declaration//GEN-END:variables
}
