/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.sangraj.lra.UI;

import com.sangraj.lra.UI.Admin.AdministratorUI;
import com.sangraj.lra.UI.Admin.USDE.SearchUI;
import javax.swing.JOptionPane;

/**
 *
 * @author Song Grudge Ranjit
 */
public class LoginUI extends javax.swing.JFrame {

    /**
     * Creates new form LoginUI
     */
    public LoginUI() {
        setTitle("Login Form");
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        txtUsername = new javax.swing.JTextField();
        txtPassword = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        btnRegister = new javax.swing.JButton();
        btnLogIn = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setLayout(null);
        jPanel1.add(txtUsername);
        txtUsername.setBounds(160, 40, 199, 30);
        jPanel1.add(txtPassword);
        txtPassword.setBounds(160, 90, 199, 30);

        jLabel2.setForeground(new java.awt.Color(204, 204, 0));
        jLabel2.setText("PASSWORD");
        jPanel1.add(jLabel2);
        jLabel2.setBounds(80, 90, 80, 30);

        jLabel1.setForeground(new java.awt.Color(204, 204, 0));
        jLabel1.setText("USERNAME");
        jPanel1.add(jLabel1);
        jLabel1.setBounds(80, 40, 79, 30);

        btnRegister.setText("REGISTER");
        btnRegister.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRegisterActionPerformed(evt);
            }
        });
        jPanel1.add(btnRegister);
        btnRegister.setBounds(221, 160, 110, 23);

        btnLogIn.setText("LOG IN");
        btnLogIn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLogInActionPerformed(evt);
            }
        });
        jPanel1.add(btnLogIn);
        btnLogIn.setBounds(110, 160, 100, 23);

        jLabel3.setIcon(new javax.swing.ImageIcon("C:\\Users\\Song Grudge Ranjit\\Pictures\\honeycomb-wallpaper-1.jpg")); // NOI18N
        jPanel1.add(jLabel3);
        jLabel3.setBounds(0, 0, 390, 220);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 390, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 221, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnLogInActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLogInActionPerformed
            String u = "admin";
                if (txtUsername.getText().isEmpty() && txtPassword.getText().isEmpty()) {
                    JOptionPane.showMessageDialog(null, "Enter Username and Password");
                }else if (txtPassword.getText().isEmpty()) {
                    JOptionPane.showMessageDialog(null, "Password");
                } else if (!txtUsername.getText().equals(u) && !txtPassword.getText().equals(u)) {
                    JOptionPane.showMessageDialog(null, "Incorrect Username or Password");
                    txtUsername.setText("");
                    txtPassword.setText("");
                } else if ( !txtPassword.getText().equals(u)) {
                    JOptionPane.showMessageDialog(null, "Incorrect Username or Password");
                    txtUsername.setText("");
                    txtPassword.setText("");
                } else if (!txtUsername.getText().equals(u)) {
                    JOptionPane.showMessageDialog(null, "Incorrect Username or Password");
                    txtUsername.setText("");
                    txtPassword.setText("");
                } else if (txtUsername.getText().equals(u) && txtPassword.getText().equals(u)) {
                    AdministratorUI aui=new AdministratorUI();
                    aui.setVisible(true);
                    setVisible(false);
                } 
    }//GEN-LAST:event_btnLogInActionPerformed

    private void btnRegisterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegisterActionPerformed
                RegistrationUI Rui = new RegistrationUI();
                Rui.setVisible(true);
                setVisible(false);
    }//GEN-LAST:event_btnRegisterActionPerformed



    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnLogIn;
    private javax.swing.JButton btnRegister;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField txtPassword;
    private javax.swing.JTextField txtUsername;
    // End of variables declaration//GEN-END:variables
}
