/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.sangraj.lra.UI;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.regex.Matcher;
import java.util.regex.Pattern;
import javax.swing.JOptionPane;

/**
 *
 * @author Song Grudge Ranjit
 */
public class RegistrationUI extends javax.swing.JFrame {
    private Pattern regexPattern;
    private Matcher regMatcher;
    /**
     * Creates new form RegistrationUI
     */
    public RegistrationUI() {
        setTitle("REGISTRATION FORM");
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        txtUsername = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        txtFirstname = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        txtMiddlename = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        txtLastname = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        txtEmail = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        txtPassword = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        txtConPassword = new javax.swing.JTextField();
        btnRegister = new javax.swing.JButton();
        btnClear = new javax.swing.JButton();
        btnBack = new javax.swing.JButton();
        jLabel8 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel2.setLayout(null);

        jLabel1.setForeground(new java.awt.Color(255, 255, 0));
        jLabel1.setText("USERNAME");
        jPanel2.add(jLabel1);
        jLabel1.setBounds(20, 20, 80, 27);
        jPanel2.add(txtUsername);
        txtUsername.setBounds(190, 20, 199, 27);

        jLabel2.setForeground(new java.awt.Color(255, 255, 0));
        jLabel2.setText("FIRST NAME");
        jPanel2.add(jLabel2);
        jLabel2.setBounds(20, 60, 80, 30);
        jPanel2.add(txtFirstname);
        txtFirstname.setBounds(190, 60, 199, 25);

        jLabel3.setForeground(new java.awt.Color(255, 255, 0));
        jLabel3.setText("MIDDLE NAME(OPTIONAL)");
        jPanel2.add(jLabel3);
        jLabel3.setBounds(17, 100, 150, 27);
        jPanel2.add(txtMiddlename);
        txtMiddlename.setBounds(190, 100, 199, 27);

        jLabel4.setForeground(new java.awt.Color(204, 204, 0));
        jLabel4.setText("LAST NAME");
        jPanel2.add(jLabel4);
        jLabel4.setBounds(20, 140, 80, 26);
        jPanel2.add(txtLastname);
        txtLastname.setBounds(190, 140, 199, 26);

        jLabel5.setForeground(new java.awt.Color(255, 255, 0));
        jLabel5.setText("EMAIL ADDRESS");
        jPanel2.add(jLabel5);
        jLabel5.setBounds(20, 180, 110, 25);
        jPanel2.add(txtEmail);
        txtEmail.setBounds(190, 180, 343, 25);

        jLabel6.setForeground(new java.awt.Color(255, 255, 0));
        jLabel6.setText("PASSWORD");
        jPanel2.add(jLabel6);
        jLabel6.setBounds(20, 220, 90, 29);
        jPanel2.add(txtPassword);
        txtPassword.setBounds(190, 220, 201, 29);

        jLabel7.setForeground(new java.awt.Color(255, 255, 0));
        jLabel7.setText("CONFIRM PASSWORD");
        jPanel2.add(jLabel7);
        jLabel7.setBounds(20, 260, 150, 25);
        jPanel2.add(txtConPassword);
        txtConPassword.setBounds(190, 260, 201, 25);

        btnRegister.setText("REGISTER");
        btnRegister.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRegisterActionPerformed(evt);
            }
        });
        jPanel2.add(btnRegister);
        btnRegister.setBounds(100, 310, 108, 30);

        btnClear.setText("CLEAR");
        btnClear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnClearActionPerformed(evt);
            }
        });
        jPanel2.add(btnClear);
        btnClear.setBounds(220, 310, 95, 30);

        btnBack.setText("BACK");
        btnBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBackActionPerformed(evt);
            }
        });
        jPanel2.add(btnBack);
        btnBack.setBounds(330, 310, 99, 30);

        jLabel8.setIcon(new javax.swing.ImageIcon("C:\\Users\\Song Grudge Ranjit\\Pictures\\honeycomb-wallpaper-1.jpg")); // NOI18N
        jPanel2.add(jLabel8);
        jLabel8.setBounds(0, 0, 580, 360);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 580, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 363, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnRegisterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegisterActionPerformed
        try {                 
                regexPattern=Pattern.compile("^[(a-zA-Z-0-9-\\_\\.)]+@[(gmail||yahoo||hotmail||outlook||live)]+\\.[(com?)]{2,3}$");
                regMatcher=regexPattern.matcher(txtEmail.getText());
                Class.forName("com.mysql.jdbc.Driver");
                Connection conn = DriverManager.getConnection("jdbc:mysql://localhost/registration", "root", null);
                String sql = "INSERT INTO tbl_registered(username,firstname,middlename,lastname,email,password) VALUES (?,?,?,?,?,?)";                             
                PreparedStatement stmt = conn.prepareStatement(sql);
                PreparedStatement stm = conn.prepareStatement("SELECT * FROM tbl_registered where email=?");
                stm.setString(1, txtEmail.getText());
                ResultSet rs =stm.executeQuery();
                PreparedStatement st=conn.prepareStatement("SELECT * FROM tbl_registered where username=?");
                st.setString(1, txtUsername.getText());
                ResultSet r=st.executeQuery();
                stmt.setString(1, txtUsername.getText());
                stmt.setString(2, txtFirstname.getText());
                stmt.setString(3, txtMiddlename.getText());
                stmt.setString(4, txtLastname.getText());
                stmt.setString(5, txtEmail.getText());
                stmt.setString(6, txtPassword.getText());
                if (txtUsername.getText().isEmpty()) {
                    JOptionPane.showMessageDialog(null, "Enter Username");
                } else if (txtFirstname.getText().isEmpty()) {
                    JOptionPane.showMessageDialog(null, "Enter your First Name");
                } else if (txtLastname.getText().isEmpty()) {
                    JOptionPane.showMessageDialog(null, "Enter your Last Name");
                } else if (txtEmail.getText().isEmpty()) {
                    JOptionPane.showMessageDialog(null, "Enter your Email Address");
                } else if (txtPassword.getText().isEmpty()) {
                    JOptionPane.showMessageDialog(null, "Password Required");
                } else if (txtConPassword.getText().isEmpty()) {
                    JOptionPane.showMessageDialog(null, "Password Confirmation Required");
                }else if(txtEmail.getText()!=null && r.next()){     
                    JOptionPane.showMessageDialog(null, "Username not available");
                    txtPassword.setText("");
                    txtConPassword.setText("");
                }else if(txtEmail.getText()!=null && !regMatcher.matches()){
                    JOptionPane.showMessageDialog(null, "Email Address is not correct");
                    txtEmail.setText("");
                    txtPassword.setText("");
                    txtConPassword.setText("");
                } else if(txtEmail.getText()!=null && rs.next()){     
                    JOptionPane.showMessageDialog(null, "Email Address already exists");
                    txtEmail.setText("");
                    txtPassword.setText("");
                   txtConPassword.setText("");
                }else if (txtPassword.getText() != null && !txtPassword.getText().equals(txtConPassword.getText())) {
                    JOptionPane.showMessageDialog(null, "Password Confirmation doesnot match");
                    txtPassword.setText("");
                    txtConPassword.setText("");
                } else if (stmt.executeUpdate() > 0) {
                    JOptionPane.showMessageDialog(null, "Registered Successfully");
                    txtUsername.setText("");
                    txtFirstname.setText("");
                    txtMiddlename.setText("");
                    txtLastname.setText("");
                    txtEmail.setText("");
                    txtPassword.setText("");
                    txtConPassword.setText("");
                }
            } catch (ClassNotFoundException | SQLException ce) {

            }
   
    }//GEN-LAST:event_btnRegisterActionPerformed

    private void btnClearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnClearActionPerformed
        txtUsername.setText("");
        txtFirstname.setText("");
        txtMiddlename.setText("");
        txtLastname.setText("");
        txtEmail.setText("");
        txtPassword.setText("");
        txtConPassword.setText("");
    }//GEN-LAST:event_btnClearActionPerformed

    private void btnBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBackActionPerformed
        LoginUI lui = new LoginUI();
        lui.setVisible(true);
        setVisible(false);
    }//GEN-LAST:event_btnBackActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBack;
    private javax.swing.JButton btnClear;
    private javax.swing.JButton btnRegister;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JTextField txtConPassword;
    private javax.swing.JTextField txtEmail;
    private javax.swing.JTextField txtFirstname;
    private javax.swing.JTextField txtLastname;
    private javax.swing.JTextField txtMiddlename;
    private javax.swing.JTextField txtPassword;
    private javax.swing.JTextField txtUsername;
    // End of variables declaration//GEN-END:variables
}
